[package]
authors = ["Josh Leverette <coder543@gmail.com>"]
name = "metric"
version = "0.1.0"

[[bench]]
harness = false
name = "bench1"

[dev-dependencies]
bencher = "0.1.2"
# dimensioned = "0.6.0"

[features]
default = ["std"]
std = []

[profile.bench]
debug = true
lto = true
